version: '3'

services:
    mydb:
        container_name: mydb
        image: mysql:5.7
        ports:
            - 3306:3306
        environment:
            - MYSQL_ROOT_HOST=${DB_HOST}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
        networks:
            - mynet

    myapp:
        container_name: myapp
        build: .
        ports:
            - 80:80
        environment:
            WAIT_HOSTS: mydb:3306
        depends_on:
            - mydb
        networks:
            - mynet

networks:
    mynet:
        driver: bridge
